export const locations = [
  "academic and residential complex",
  "addams hall",
  "behavioral sciences building",
  "burnham hall",
  "douglass hall",
  "grant hall",
  "henry hall",
  "lecture center building a",
  "lecture center building b",
  "lecture center building c",
  "lecture center building d",
  "lecture center building e",
  "lecture center building f",
  "lincoln hall",
  "stevenson hall",
  "university hall",
  "taft hall",
  "commons south",
  "science and engineering labratory west",
  "science and engineering labratory east",
  "uic student center east",
  "richard j daley library",
];
