import { Item } from "../schemas/itemSchema";

export const sampleItems: Item[] = [
  {
    id: "1",
    name: "Blue Backpack",
    description: "A navy blue Jansport backpack with a laptop inside",
    price: 49.99,
    image_url: "/placeholder.svg?height=100&width=100",
    location: "Library",
    weather: "Clear",
    created_at: new Date("2023-06-01"),
    updated_at: new Date("2023-06-01"),
    user_id: "user1",
    category: "Bag",
    is_available: true,
  },
  {
    id: "2",
    name: "iPhone 12",
    description: "Black iPhone 12 with a cracked screen protector",
    price: 299.99,
    image_url: "/placeholder.svg?height=100&width=100",
    location: "Cafeteria",
    weather: "Sunny",
    created_at: new Date("2023-06-02"),
    updated_at: new Date("2023-06-02"),
    user_id: "user2",
    category: "Electronics",
    is_available: false,
  },
  {
    id: "3",
    name: "Car Keys",
    description: "Honda car keys with a red lanyard",
    price: 5.99,
    image_url: "/placeholder.svg?height=100&width=100",
    location: "Parking Lot",
    weather: "Cloudy",
    created_at: new Date("2023-06-03"),
    updated_at: new Date("2023-06-03"),
    user_id: "user3",
    category: "Keys",
    is_available: true,
  },
  {
    id: "4",
    name: "Textbook",
    description: "Introduction to Psychology textbook",
    price: 30.0,
    image_url: "/placeholder.svg?height=100&width=100",
    location: "Classroom 101",
    weather: "Rainy",
    created_at: new Date("2023-06-04"),
    updated_at: new Date("2023-06-04"),
    user_id: "user4",
    category: "Book",
    is_available: true,
  },
  {
    id: "5",
    name: "Water Bottle",
    description: "Blue Hydro Flask water bottle",
    price: 40.0,
    image_url: "/placeholder.svg?height=100&width=100",
    location: "Gym",
    weather: "Hot",
    created_at: new Date("2023-06-05"),
    updated_at: new Date("2023-06-05"),
    user_id: "user5",
    category: "Accessories",
    is_available: true,
  },
];
