export const TITLE_TAILWIND_CLASS = "text-2xl sm:text-2xl md:text-3xl lg:text-4xl"

export const Brands = [
    "Apple",
    "Samsung",
    "Dell",
    "HP",
    "Lenovo",
    "Microsoft",
    "Nike",
    "Adidas",
    "Sony",
    "JBL",
    "Beats",
    "Asus",
    "Butun",
    "Other",
    "Hymy Sports",
    "Texas Instruments",
    "Jabra",
  ];

  export const Categories = [
    "Personal",
    "Electronics",
    "Clothing",
    "Documents & IDs",
    "Locks",
    "Bags",
    "Jewelry & Watches",
    "Sports",
    "Games",
    "Books & Media",
    "Household",
    "Tools",
    "Vehicles",
    "Office",
    "Medical",
    "Pet",
    "Outdoor",
    "Travel",
    "Collectibles",
    "Miscellaneous",
  ];

  export const Colors = [
    "Red",
    "Blue",
    "Green",
    "Black",
    "Navy",
    "White",
    "Gray",
    "Yellow",
    "Purple",
    "Pink",
    "Orange",
    "Brown",
    "Silver",
  ];

  export const Keywords = [
    "Airplane",
    "Alarm clock",
    "Angel",
    "Ant",
    "Apple",
    "Arm",
    "Armchair",
    "Ashtray",
    "Axe",
    "Backpack",
    "Banana",
    "Barn",
    "Baseball bat",
    "Basket",
    "Bathtub",
    "Bear (animal)",
    "Bed",
    "Bee",
    "Beer-mug",
    "Bell",
    "Bench",
    "Bicycle",
    "Binoculars",
    "Blimp",
    "Book",
    "Bookshelf",
    "Boomerang",
    "Bottle opener",
    "Bowl",
    "Brain",
    "Bread",
    "Bridge",
    "Bulldozer",
    "Bus",
    "Bush",
    "Butterfly",
    "Cabinet",
    "Cactus",
    "Cake",
    "Calculator",
    "Camel",
    "Camera",
    "Candle",
    "Cannon",
    "Canoe",
    "Car (sedan)",
    "Carrot",
    "Castle",
    "Cat",
    "Cell phone",
    "Chair",
    "Chandelier",
    "Church",
    "Cigarette",
    "Cloud",
    "Comb",
    "Computer monitor",
    "Computer-mouse",
    "Couch",
    "Cow",
    "Crab",
    "Crane (machine)",
    "Crocodile",
    "Crown",
    "Cup",
    "Diamond",
    "Dog",
    "Dolphin",
    "Donut",
    "Door",
    "Door handle",
    "Dragon",
    "Duck",
    "Ear",
    "Elephant",
    "Envelope",
    "Eye",
    "Eyeglasses",
    "Face",
    "Fan",
    "Feather",
    "Filelist.txt",
    "Fire hydrant",
    "Fish",
    "Flashlight",
    "Floor lamp",
    "Flower with stem",
    "Flying bird",
    "Flying saucer",
    "Foot",
    "Fork",
    "Frog",
    "Frying-pan",
    "Giraffe",
    "Grapes",
    "Grenade",
    "Guitar",
    "Hamburger",
    "Hammer",
    "Hand",
    "Harp",
    "Hat",
    "Head",
    "Head-phones",
    "Hedgehog",
    "Helicopter",
    "Helmet",
    "Horse",
    "Hot air balloon",
    "Hot-dog",
    "Hourglass",
    "House",
    "Human-skeleton",
    "Ice-cream-cone",
    "Ipod",
    "Kangaroo",
    "Key",
    "Keyboard",
    "Knife",
    "Ladder",
    "Laptop",
    "Leaf",
    "Lightbulb",
    "Lighter",
    "Lion",
    "Lobster",
    "Loudspeaker",
    "Mailbox",
    "Megaphone",
    "Mermaid",
    "Microphone",
    "Microscope",
    "Monkey",
    "Moon",
    "Mosquito",
    "Motorbike",
    "Mouse (animal)",
    "Mouth",
    "Mug",
    "Mushroom",
    "Nose",
    "Octopus",
    "Owl",
    "Palm tree",
    "Panda",
    "Paper clip",
    "Parachute",
    "Parking meter",
    "Parrot",
    "Pear",
    "Pen",
    "Penguin",
    "Person sitting",
    "Person walking",
    "Piano",
    "Pickup truck",
    "Pig",
    "Pigeon",
    "Pineapple",
    "Pipe (for smoking)",
    "Pizza",
    "Potted plant",
    "Power outlet",
    "Present",
    "Pretzel",
    "Pumpkin",
    "Purse",
    "Rabbit",
    "Race car",
    "Radio",
    "Rainbow",
    "Revolver",
    "Rifle",
    "Rollerblades",
    "Rooster",
    "Sailboat",
    "Santa claus",
    "Satellite",
    "Satellite dish",
    "Saxophone",
    "Scissors",
    "Scorpion",
    "Screwdriver",
    "Sea turtle",
    "Seagull",
    "Shark",
    "Sheep",
    "Ship",
    "Shoe",
    "Shovel",
    "Skateboard",
    "Skull",
    "Skyscraper",
    "Snail",
    "Snake",
    "Snowboard",
    "Snowman",
    "Socks",
    "Space shuttle",
    "Speed-boat",
    "Spider",
    "Sponge bob",
    "Spoon",
    "Squirrel",
    "Standing bird",
    "Stapler",
    "Strawberry",
    "Streetlight",
    "Submarine",
    "Suitcase",
    "Sun",
    "Suv",
    "Swan",
    "Sword",
    "Syringe",
    "T-shirt",
    "Table",
    "Tablelamp",
    "Teacup",
    "Teapot",
    "Teddy-bear",
    "Telephone",
    "Tennis-racket",
    "Tent",
    "Tiger",
    "Tire",
    "Toilet",
    "Tomato",
    "Tooth",
    "Toothbrush",
    "Tractor",
    "Traffic light",
    "Train",
    "Tree",
    "Trombone",
    "Trousers",
    "Truck",
    "Trumpet",
    "Tv",
    "Umbrella",
    "Van",
    "Vase",
    "Violin",
    "Walkie talkie",
    "Wheel",
    "Wheelbarrow",
    "Windmill",
    "Wine-bottle",
    "Wineglass",
    "Wrist-watch",
    "Zebra"
  ];

  export const Locations = [
    {
      name: "Academic and Residential Complex",
      lat: 41.8745,
      lng: -87.6506,
    },
    {
      name: "Student Center East",
      lat: 41.87176450337234,
      lng: -87.64807327722833,
    },
    {
      name: "Addams Hall",
      lat: 41.87094498558426,
      lng: -87.64900121806708,
    },
    {
      name: "Behavioral Sciences Building",
      lat: 41.87376360399818,
      lng: -87.65227190551478,
    },
    {
      name: "Burnham Hall",
      lat: 41.87100362474029,
      lng: -87.6495352193654,
    },
    {
      name: "Grant Hall",
      lat: 41.87284225473778,
      lng: -87.6494501829802,
    },
    {
      name: "Henry Hall",
      lat: 41.874071812543406,
      lng: -87.65055054595406,
    },
    {
      name: "Lecture Center A",
      lat: 41.8720486206541,
      lng: -87.64984441230222,
    },
    {
      name: "Lecture Center B",
      lat: 41.872207865461185,
      lng: -87.6491750418909,
    },
    {
      name: "Lecture Center C",
      lat: 41.872097998238374,
      lng: -87.6487891032567,
    },
    {
      name: "Lecture Center D",
      lat: 41.871630274234924,
      lng: -87.64866477932077,
    },
    {
      name: "Lecture Center E",
      lat: 41.87162292636316,
      lng: -87.64922837510224,
    },
    {
      name: "Lecture Center F",
      lat: 41.87164903041386,
      lng: -87.64984405127318,
    },
    {
      name: "Lincoln Hall",
      lat: 41.872494749530794,
      lng: -87.64943815815064,
    },
    {
      name: "Stevenson Hall",
      lat: 41.8728430083608,
      lng: -87.65033734601529,
    },
    {
      name: "University Hall",
      lat: 41.873858,
      lng: -87.651203,
    },
    {
      name: "Taft Hall",
      lat: 1.871283,
      lng: -87.649517,
    },
    {
      name: "Commons South",
      lat: 41.873326,
      lng: -87.647538,
    },
    {
      name: "Science and Engineering Laboratory West",
      lat: 41.870433,
      lng: -87.649206,
    },
    {
      name: "Science and Engineering Laboratory East",
      lat: 41.870933,
      lng: -87.648484,
    },
    {
      name: "UIC Student Center East",
      lat: 41.871899,
      lng: -87.648206,
    },
    {
      name: "Richard J Daley Library",
      lat: 41.8718,
      lng: -87.650158,
    },
  ];
  
  export const defaultLocation = {
    name: "Academic and Residential Complex",
    lat: 41.8745,
    lng: -87.6506,
  };

  export const Materials = [
    "Plastic",
    "Metal",
    "Fabric",
    "Leather",
    "Wood",
    "Glass",
    "Ceramic",
    "Rubber",
    "Composite",
    "Synthetic",
    "Unknown",
    "Edible",
  ];

  export const Weather = [
    "Sunny",
    "Partly cloudy",
    "Cloudy",
    "Rainy",
    "Stormy",
    "Snowy",
    "Windy",
    "Foggy",
  ];
  