categories = [
    # Personal Items
    "personal",
    "wallet",
    "purse",
    "keys",
    "id card",
    "student id",
    "credit cards",
    "cash",
    "makeup",
    "glasses",
    "sunglasses",
    "umbrella",
    "water bottle",

    # Electronics
    "electronics",
    "laptop",
    "phone",
    "tablet",
    "smartwatch",
    "headphones",
    "earbuds",
    "charger",
    "power bank",
    "calculator",
    "camera",
    "usb drive",
    "hard drive",

    # Clothing & Accessories
    "clothing",
    "jacket",
    "hoodie",
    "sweater",
    "shirt",
    "pants",
    "shorts",
    "shoes",
    "boots",
    "hat",
    "cap",
    "scarf",
    "gloves",
    "socks",
    "jewelry & watches",
    "ring",
    "necklace",
    "bracelet",
    "watch",
    "earrings",

    # Documents & IDs
    "documents & ids",
    "passport",
    "driver license",
    "student id",
    "credit card",
    "debit card",
    "insurance card",
    "membership card",
    "transit card",

    # Bags & Storage
    "bags",
    "backpack",
    "laptop bag",
    "messenger bag",
    "duffel bag",
    "tote bag",
    "suitcase",
    "gym bag",
    "lunch box",
    "pencil case",

    # Academic & Office
    "books & media",
    "textbook",
    "notebook",
    "binder",
    "folder",
    "planner",
    "office",
    "stationery",
    "calculator",

    # Sports & Recreation
    "sports",
    "gym equipment",
    "water bottle",
    "tennis racket",
    "basketball",
    "soccer ball",
    "yoga mat",
    "outdoor",
    "travel",

    # Other Categories
    "locks",
    "games",
    "household",
    "tools",
    "vehicles",
    "medical",
    "pet",
    "collectibles",
    "miscellaneous"
]