locations = [
    # Main Buildings
    "academic and residential complex",
    "addams hall",
    "behavioral sciences building",
    "burnham hall",
    "douglass hall",
    "grant hall",
    "henry hall",
    "lecture center building a",
    "lecture center building b",
    "lecture center building c",
    "lecture center building d",
    "lecture center building e",
    "lecture center building f",
    "library",
    "lincoln hall",
    "stevenson hall",
    "university hall",
    "taft hall",
    "commons south",
    "science and engineering labratory west",
    "science and engineering labratory east",
    "uic student center east",
    "richard j daley library",
    "arc",
    "bsb",
    "sce",
    "sele",

    # Common Campus Areas
    "student center",
    "cafeteria",
    "dining hall",
    "study room",
    "computer lab",
    "gym",
    "recreation center",
    "fitness center",
    "bookstore",
    "coffee shop",
    "food court",
    
    # Outdoor Locations
    "quad",
    "courtyard",
    "parking lot",
    "bus stop",
    "bike rack",
    "plaza",
    "garden",
    "stadium",
    "sports field",
    
    # Building Areas
    "lobby",
    "hallway",
    "restroom",
    "lounge",
    "auditorium",
    "classroom",
    "laboratory",
    "office",
    "conference room"
]